### ISSUE TITLE
Cannot resolve symbol/method

### ISSUE THREAD

**Issue by redyana18** [rajatgupta1998/android_packages_apps_Updater#1]
Hi rajatgupta1998. I am working on an android application for Update App. I'm having difficulty with:
import android.os.UpdateEngine
import android.os.UpdateEngineCallback
import android.os.SystemProperties.
I have checked in the sdk folder the UpdateEngine, UpdateEngineCallback, SystemProperties files are available but when I read them in Android Studio they are not included in the list. Any solution for this?

**Comment by rajatgupta1998** [comment]
> Hi rajatgupta1998. I am working on an android application for Update App. I'm having difficulty with: import android.os.UpdateEngine import android.os.UpdateEngineCallback import android.os.SystemProperties. I have checked in the sdk folder the UpdateEngine, UpdateEngineCallback, SystemProperties files are available but when I read them in Android Studio they are not included in the list. Any solution for this?

Hey there, this project is too outdated as of today. Hence I recommend you to take a look at newer AOSP/LineageOS based sources for this app.

All that being said, the classes  you have mentioned are not part of Android SDK, they are a part of AOSP and only System Apps can access them. If you want to build this app in Android Studio, you will have to add these classes into a JAR file and then add it as a compiletime dependency in the app project.

**Comment by redyana18** [comment]
Thank you for the suggestions and answers
